### ISSUE TITLE
Warning: unrecognized cop Naming/BinaryOperatorParameter found in ~/.gem/ruby/2.4.2/gems/bixby-0.3.0/bixby_default.yml

### ISSUE THREAD

**Issue by hackmastera** [samvera-labs/bixby#14]
Getting this warning when I run rubocop with bixby 0.3.0. rubocop still completes and passes.

**Comment by no-reply** [comment]
Which versions of rubocop are you seeing this with?

**Comment by hackmastera** [comment]
This is probably a dup of #10.
