### ISSUE TITLE
Error: The `Lint/InvalidCharacterLiteral` cop has been removed since it was never being actually triggered. (obsolete configuration found in /home/ubuntu/valkyrie/valkyrie/vendor/valk_bundle/ruby/2.3.0/gems/bixby-0.3.0/bixby_default.yml, please update it)

### ISSUE THREAD

**Issue by hackmastera** [samvera-labs/bixby#15]
This unfortunately does appear to abort the rest of the rubocop run and fail the test suite.

**Comment by hackmastera** [comment]
example: https://circleci.com/gh/samvera-labs/valkyrie/625

**Comment by no-reply** [comment]
@hackmastera which version(s) of `rubocop` does this effect?

**Comment by hackmastera** [comment]
@no-reply oh, that is a good point it effects unreleased rubocop.

Valkyrie is pinned to a SHA that was merged to master a few days ago: https://github.com/bbatsov/rubocop/commit/178b3150b7610195c327783575177520316e1985

If possible I could remove the value via local override; it seems like I'd have to somehow override the entire file to remove it.

Alternatively, it sounds from the error message that removing it now would be fine -- "it was never actually being triggered"

**Comment by no-reply** [comment]
Yeah, part of the point of the new versioning strategy is to lock support down. RuboCop has been extremely volatile, and we felt the need to insulate users from breaking changes on point releases and limit maintenance scope here.

> Alternatively, it sounds from the error message that removing it now would be fine -- "it was never actually being triggered"

Yes, but I'm wondering if this requires a new release on the 0.x series?

**Comment by hackmastera** [comment]
It seems like it would make sense to release it as 0.4.0 in case you need to add anything else to the 0.3.0 to support actually-released rubocops.

**Comment by hackmastera** [comment]
But it also seems like it would be fine at 0.3.1 since it is compatible with currently-released rubocops.
