### ISSUE TITLE
Removal of Rubocop Cop that is stopping the build process.

### ISSUE THREAD

**Issue by bwatson78** [samvera-labs/bixby#71]
### Descriptive summary

For Bixby v4.0.0, the error below occurs when attempting to build an application (in this case, Hyrax `bl7bootstrap4` branch) that runs off of Ruby 2.7.4. 
```
Error: unrecognized cop or department Lint/UselessElseWithoutRescue found in vendor/bundle/ruby/2.7.0/gems/bixby-4.0.0/bixby_default.yml
Did you mean `Lint/UselessSetterCall`?
```
After researching, I found that the latest version of Rubocop (a Bixby dependency) has removed this Cop because Ruby v2.6+ has stopped allowing the use of `begin...else` syntax. Reference: [https://github.com/rubocop/rubocop/pull/10577](https://github.com/rubocop/rubocop/pull/10577)

### Rationale

The presence of `Lint/UselessElseWithoutRescue` in the `bixby_default.yml` file is preventing the application building process.

**Comment by no-reply** [comment]
cc: @cjcolvar it looks like we can't trust RuboCop even after 1.0.0.

**Comment by no-reply** [comment]
thanks @bwatson78. in the past, Bixby was locked to specific versions of RuboCop to protect its users from RuboCop's frequent breaking changes. we thought with the release of RuboCop 1.0 those changes would stop, but it looks like not.

i think the appropriate fix is to lock Bixby back on a version of RuboCop that works.
